version: "3.9"

networks:
    frontend:
    backend:

services:
  mariadb:
    container_name: ais-mariadb
    build: mariadb
    image: ais-mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DBPASS}
    ports:
      - "3307:3306"
    volumes:
      - ais-data
    networks:
      - ais-network

  node:
    container_name: ais-node
    build: webapp
    image: ais-webapp
    restart: always
    tty: true
    networks:
      - ais-network
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

