networks:
  ais-network:

volumes:
  mariadb:
  uwsgi-data:
  web-static:
  ais-django:
    driver: local
    driver_opts:
      type: none
      device: ${SRCDIR}/django
      o: bind

services:
  mariadb:
    hostname: mariadb
    container_name: ais-mariadb
    build: mariadb
    image: ais-mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DBPASS}
    ports:
      - "3307:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - ais-network

  django:
    hostname: django
    container_name: ais-django
    build: django
    image: ais-django
    restart: always
    tty: true
    environment:
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      WAN_IP: ${WAN_IP}
      ULP_URL: ${ULP_URL}
    volumes:
      - uwsgi-data:/tmp/uwsgi
      - web-static:/var/www/ais/static
      - ais-django:/ais/django
    networks:
      - ais-network
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

