version: "3.9"

networks:
  backend:

volumes:
  mariadb:
  invoices:

services:
  mariadb:
    hostname: mariadb
    container_name: ais-mariadb
    build: mariadb
    image: ais-mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DBPASS}
    ports:
      - "3307:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

  webapp:
    hostname: webapp
    container_name: ais-webapp
    build: webapp
    image: ais-webapp
    restart: always
    tty: true
    volumes:
      - invoices:/ais/invoices
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

