# Generated by Django 5.0.4 on 2024-04-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="TaxPeriod",
        ),
        migrations.DeleteModel(
            name="Travel",
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["name", "bsb", "number"]},
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "managed": False,
                "ordering": ["-date", "activity_type"],
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="activitytype",
            options={"managed": False, "ordering": ["description", "rate"]},
        ),
        migrations.AlterModelOptions(
            name="billing",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"managed": False, "ordering": ["billing", "-created"]},
        ),
    ]
