# Generated by Django 5.0.4 on 2024-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("invoice", "0002_delete_expense_delete_taxperiod_delete_travel_and_more"),
        ("invoice", "0003_alter_account_options"),
        ("invoice", "0004_alter_account_options"),
        ("invoice", "0005_alter_account_bsb_alter_account_name_and_more"),
        ("invoice", "0006_alter_activity_options"),
        ("invoice", "0007_alter_activity_options_alter_activitytype_options"),
        ("invoice", "0008_alter_activity_options_and_more"),
        ("invoice", "0009_alter_activity_options"),
        ("invoice", "0010_alter_activity_options"),
        ("invoice", "0011_alter_account_options_alter_activity_options_and_more"),
    ]

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="TaxPeriod",
        ),
        migrations.DeleteModel(
            name="Travel",
        ),
        migrations.AlterModelOptions(
            name="billing",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"managed": False, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"managed": False, "ordering": ["billing", "-created"]},
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["name", "bsb", "number"]},
        ),
        migrations.AlterField(
            model_name="account",
            name="bsb",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelOptions(
            name="activitytype",
            options={"ordering": ["description", "rate"]},
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="description",
            field=models.CharField(default="Add a description", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"managed": False, "ordering": ["name", "bsb", "number"]},
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "managed": False,
                "ordering": ["-date", "activity_type"],
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="activitytype",
            options={"managed": False, "ordering": ["description", "rate"]},
        ),
    ]
