# Generated by Django 5.0.4 on 2024-04-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_delete_expense_delete_taxperiod_delete_travel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"managed": False, "ordering": ["name", "bsb", "number"]},
        ),
    ]
