# Generated by Django 5.0.4 on 2024-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_alter_account_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bsb",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.CharField(max_length=255),
        ),
    ]
