# Generated by Django 5.0.4 on 2024-04-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_alter_account_bsb_alter_account_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-date", "activity_type"],
                "verbose_name_plural": "Activities",
            },
        ),
    ]
