# Generated by Django 5.0.4 on 2024-04-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_alter_activity_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "managed": False,
                "ordering": ["-date", "activity_type"],
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="activitytype",
            options={"ordering": ["description", "rate"]},
        ),
    ]
